#!/bin/bash

if [ -t 1 ]; then
    txtblu=$(tput setaf 6) # Blue Text
    txtrst=$(tput sgr0)    # Text Reset
    echo ${txtblu}  # Yay fancy colours!
fi

if [ -z "$1" ]; then
    echo "+-------------------------------------------------------+"
    echo "|          Snazz's Awesome RDiff Rollup Script          |"
    echo "+-------------------------------------------------------+"
    echo "| I should write a better description here, but in      |"
    echo "| this script uses RDiff to delete backups for the      |"
    echo "| target server older than a certain date.              |"
    echo "|                                                       |"
    echo "| Run this from the /supers home directory.             |"
    echo "|   usage:                                              |"
    echo "|        rdrollup <serverpath> <timerange>              |"
    echo "|   example:                                            |"
    echo "|        rdrollup /minecraft/April_Main 48h             |"
    echo "|   effect:                                             |"
    echo "|        runs the following command:                    |"
    echo "|        rdiff-backup --remove-older-than <timerange>   |"
    echo "|          <backuppath>                                 |"
    echo "+-------------------------------------------------------+"
    echo ${txtrst}
    exit
fi

echo "-------------------------------------------"
echo "--       RDRollup - by AgentSnazz        --"
echo "-------------------------------------------"
echo "-- $(date +%Y-%m-%d-%H%M)"

# Identify backup path.
SERVERDIR=$1
echo "-- Server Dir = $SERVERDIR"
# `minecraft/janperm` becomes `janperm`
WORLD=${SERVERDIR##*/}
echo "-- World = $WORLD"
BACKUPS="/backup/$WORLD/backup"
echo "-- Backups = $BACKUPS"


# Deleted old incrementals older than the specified time
echo "-- Deleting Old Incrementals..."
rdiff-backup --force --remove-older-than $2 $BACKUPS
echo "-- Old Incrementals Deleted"

# Deleting old dailies older than 7 days
echo "-- Deleting Old Dailies..."
find /backup/$WORLD/$WORLD*.tar.gz -maxdepth 0 -type f -mtime +6 -delete
echo "-- Old Dalies Deleted"

# Create Weekly backup by copying Monday morning's daily

# Only keep 7 most recent dailies

echo "-- RDRollup script complete"
echo "-------------------------------------------"

if [ -t 1 ]; then
    echo ${txtrst}
fi
