#!/bin/bash

if [ -t 1 ]; then
    txtblu=$(tput setaf 6) # Blue Text
    txtrst=$(tput sgr0)    # Text Reset
    echo ${txtblu}  # Yay fancy colours!
fi

if [ -z "$1" ]; then
    echo "+-------------------------------------------------------+"
    echo "| Snazz's Awesome RDiff Incremental Backup Script       |"
    echo "+-------------------------------------------------------+"
    echo "| I should write a better description here, but in      |"
    echo "| this script uses RDiff to make an incremental backup  |"
    echo "| of the target server running in a screen.             |"
    echo "|                                                       |"
    echo "| Run this from the /supers home directory.             |"
    echo "|   usage:                                              |"
    echo "|        rdincremental <ServerScreen> <ServerPath>      |"
    echo "|   example:                                            |"
    echo "|        rdincremental server /minecraft/April_Main     |"
    echo "+-------------------------------------------------------+"
    echo ${txtrst}
    exit
fi

SCREEN=$1 # I should really add some error checking to this line.

echo "-------------------------------------------"
echo "--     RDIncremental - by AgentSnazz     --"
echo "-------------------------------------------"
echo "-- $(date +%Y-%m-%d-%H%M)"

# Warn players in game of impending action.
screen -p 0 -S $SCREEN -X eval 'stuff "broadcast Starting Automated Backup, Do Not Be Alarmed."\015'

# Identify target directory and prepare destination path.
SOURCE=$2
echo "-- Source = $SOURCE"
# `minecraft/janperm` becomes `janperm`
WORLD=${SOURCE##*/}
echo "-- World = $WORLD"
DEST="/backup/$WORLD"
mkdir -p $DEST
echo "-- Dest = $DEST"

# Saves all chunks on the server.
echo "-- Saving chunks..."
screen -p 0 -S $SCREEN -X eval 'stuff "save-off"\015'
screen -p 0 -S $SCREEN -X eval 'stuff "save-all"\015'
echo "-- Chunks saved"

# Creates a backup, with incremental data stored in a subfolder
echo "-- Creating incremental backup..."
rdiff-backup $SOURCE $DEST/backup
echo "-- RDiff Incremental Created"

# Notify players in game that activity affecting them is complete.
screen -p 0 -S $SCREEN -X eval 'stuff "save-on"\015'
screen -p 0 -S $SCREEN -X eval 'stuff "broadcast Automated Backup Complete, Carry On."\015'

echo "-- RDIncremental script complete"
echo "-------------------------------------------"

if [ -t 1 ]; then
    echo ${txtrst}
fi
